"""添加文章模型

Revision ID: 5193adb4fd9c
Revises: cba185536208
Create Date: 2026-01-15 13:34:14.619791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5193adb4fd9c'
down_revision: Union[str, Sequence[str], None] = 'cba185536208'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('art',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=False),
    sa.Column('artcontent', sa.String(length=5000), nullable=False),
    sa.Column('thumbnail', sa.LargeBinary(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_art'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('art')
    # ### end Alembic commands ###
