"""增加产品模型一个产品编号的信息

Revision ID: 563b88c82ca2
Revises: d51d30653b95
Create Date: 2026-01-23 09:26:15.892319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '563b88c82ca2'
down_revision: Union[str, Sequence[str], None] = 'd51d30653b95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('productno', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'productno')
    # ### end Alembic commands ###
