"""order模型忘了加与公司之间的关系

Revision ID: 6957cff5cbcb
Revises: 9afdda973b1c
Create Date: 2026-01-22 16:30:50.487591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6957cff5cbcb'
down_revision: Union[str, Sequence[str], None] = '9afdda973b1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
