"""update_models

Revision ID: cba185536208
Revises: 08369504438d
Create Date: 2026-01-14 15:43:33.679566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cba185536208'
down_revision: Union[str, Sequence[str], None] = '08369504438d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_code', sa.Column('type', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_code', 'type')
    # ### end Alembic commands ###
