"""增加产品模型一个库存的信息

Revision ID: d51d30653b95
Revises: 6957cff5cbcb
Create Date: 2026-01-23 09:23:10.642455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd51d30653b95'
down_revision: Union[str, Sequence[str], None] = '6957cff5cbcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('storenum', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'storenum')
    # ### end Alembic commands ###
